// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/settings.dart';
import 'api/sftp.dart';
import 'api/terminal.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<SftpProgress> dco_decode_StreamSink_sftp_progress_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<TermEvent> dco_decode_StreamSink_term_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  TermFrame dco_decode_box_autoadd_term_frame(dynamic raw);

  @protected
  TermSize dco_decode_box_autoadd_term_size(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SftpFileEntry> dco_decode_list_sftp_file_entry(dynamic raw);

  @protected
  List<TermLine> dco_decode_list_term_line(dynamic raw);

  @protected
  List<TermRun> dco_decode_list_term_run(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  TermFrame? dco_decode_opt_box_autoadd_term_frame(dynamic raw);

  @protected
  SftpFileEntry dco_decode_sftp_file_entry(dynamic raw);

  @protected
  SftpProgress dco_decode_sftp_progress(dynamic raw);

  @protected
  TermEvent dco_decode_term_event(dynamic raw);

  @protected
  TermFrame dco_decode_term_frame(dynamic raw);

  @protected
  TermLine dco_decode_term_line(dynamic raw);

  @protected
  TermRun dco_decode_term_run(dynamic raw);

  @protected
  TermSize dco_decode_term_size(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<SftpProgress> sse_decode_StreamSink_sftp_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TermEvent> sse_decode_StreamSink_term_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  TermFrame sse_decode_box_autoadd_term_frame(SseDeserializer deserializer);

  @protected
  TermSize sse_decode_box_autoadd_term_size(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SftpFileEntry> sse_decode_list_sftp_file_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<TermLine> sse_decode_list_term_line(SseDeserializer deserializer);

  @protected
  List<TermRun> sse_decode_list_term_run(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  TermFrame? sse_decode_opt_box_autoadd_term_frame(
    SseDeserializer deserializer,
  );

  @protected
  SftpFileEntry sse_decode_sftp_file_entry(SseDeserializer deserializer);

  @protected
  SftpProgress sse_decode_sftp_progress(SseDeserializer deserializer);

  @protected
  TermEvent sse_decode_term_event(SseDeserializer deserializer);

  @protected
  TermFrame sse_decode_term_frame(SseDeserializer deserializer);

  @protected
  TermLine sse_decode_term_line(SseDeserializer deserializer);

  @protected
  TermRun sse_decode_term_run(SseDeserializer deserializer);

  @protected
  TermSize sse_decode_term_size(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sftp_progress_Sse(
    RustStreamSink<SftpProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_term_event_Sse(
    RustStreamSink<TermEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_term_frame(
    TermFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_term_size(
    TermSize self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sftp_file_entry(
    List<SftpFileEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_term_line(List<TermLine> self, SseSerializer serializer);

  @protected
  void sse_encode_list_term_run(List<TermRun> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_term_frame(
    TermFrame? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sftp_file_entry(SftpFileEntry self, SseSerializer serializer);

  @protected
  void sse_encode_sftp_progress(SftpProgress self, SseSerializer serializer);

  @protected
  void sse_encode_term_event(TermEvent self, SseSerializer serializer);

  @protected
  void sse_encode_term_frame(TermFrame self, SseSerializer serializer);

  @protected
  void sse_encode_term_line(TermLine self, SseSerializer serializer);

  @protected
  void sse_encode_term_run(TermRun self, SseSerializer serializer);

  @protected
  void sse_encode_term_size(TermSize self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
