// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/settings.dart';
import 'api/sftp.dart';
import 'api/terminal.dart';
import 'api/update.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 790256588;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'cterminal_rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiUpdateAppVersion();

  String crateApiSettingsColorSchemes();

  String crateApiSettingsConfigDefaults();

  String crateApiSettingsConfigFilePath();

  Future<String> crateApiSettingsConfigLoad();

  Future<String> crateApiSettingsConfigSave({required String json});

  Future<String> crateApiSettingsDefaultProfile();

  String crateApiSftpDownloadsDir();

  String crateApiSettingsHighlightPatternError({required String pattern});

  Future<String> crateApiSettingsProfilesList();

  Future<void> crateApiSettingsSecretDelete({
    required String kind,
    required String profileId,
  });

  Future<bool> crateApiSettingsSecretExists({
    required String kind,
    required String profileId,
  });

  Future<void> crateApiSettingsSecretSet({
    required String kind,
    required String profileId,
    required String value,
  });

  Future<List<String>> crateApiSettingsSerialPorts();

  void crateApiSettingsSetLanguage({required String code});

  Future<void> crateApiSftpSftpClose({required int id});

  Stream<SftpProgress> crateApiSftpSftpDownload({
    required int id,
    required String remote,
    required String local,
  });

  Future<String> crateApiSftpSftpHome({required int id});

  Future<List<SftpFileEntry>> crateApiSftpSftpList({
    required int id,
    required String path,
  });

  Future<void> crateApiSftpSftpMkdir({required int id, required String path});

  Future<int> crateApiSftpSftpOpen({required int termId});

  Future<void> crateApiSftpSftpRemove({
    required int id,
    required String path,
    required bool isDir,
  });

  Future<void> crateApiSftpSftpRename({
    required int id,
    required String from,
    required String to,
  });

  Stream<SftpProgress> crateApiSftpSftpUpload({
    required int id,
    required String local,
    required String remote,
  });

  String crateApiSettingsShellPath({
    required String path,
    required String profileJson,
  });

  Future<String> crateApiSettingsStateLoad();

  Future<void> crateApiSettingsStateSave({required String json});

  void crateApiTerminalTermApplySettings();

  void crateApiTerminalTermClear({required int id});

  void crateApiTerminalTermClose({required int id});

  String crateApiTerminalTermCwd({required int id});

  TermFrame? crateApiTerminalTermFrame({required int id});

  void crateApiTerminalTermInput({required int id, required List<int> data});

  bool crateApiTerminalTermKey({
    required int id,
    required String key,
    required String text,
    required int mods,
    required bool altIsMeta,
  });

  String crateApiTerminalTermLineText({required int id, required int row});

  bool crateApiTerminalTermMouse({
    required int id,
    required int action,
    required int button,
    required int col,
    required int row,
    required int mods,
  });

  Stream<TermEvent> crateApiTerminalTermOpen({
    required int id,
    required String profileJson,
    required TermSize size,
  });

  void crateApiTerminalTermPaste({required int id, required String text});

  void crateApiTerminalTermResize({required int id, required TermSize size});

  void crateApiTerminalTermScroll({
    required int id,
    required int lines,
    required int col,
    required int row,
  });

  void crateApiTerminalTermScrollOffset({required int id, required int offset});

  void crateApiTerminalTermScrollTo({required int id, required String target});

  bool crateApiTerminalTermSearch({
    required int id,
    required String pattern,
    required bool backwards,
  });

  void crateApiTerminalTermSearchClear({required int id});

  void crateApiTerminalTermSelectAll({required int id});

  void crateApiTerminalTermSelectClear({required int id});

  void crateApiTerminalTermSelectStart({
    required int id,
    required int col,
    required int row,
    required bool rightHalf,
    required int kind,
  });

  void crateApiTerminalTermSelectUpdate({
    required int id,
    required int col,
    required int row,
    required bool rightHalf,
  });

  String? crateApiTerminalTermSelectionText({required int id});

  void crateApiTerminalTermZmodemUpload({
    required int id,
    required List<String> paths,
  });

  Future<UpdateInfo?> crateApiUpdateUpdateCheckDaily();

  Future<UpdateInfo> crateApiUpdateUpdateCheckNow();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiUpdateAppVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUpdateAppVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateAppVersionConstMeta =>
      const TaskConstMeta(debugName: "app_version", argNames: []);

  @override
  String crateApiSettingsColorSchemes() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsColorSchemesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsColorSchemesConstMeta =>
      const TaskConstMeta(debugName: "color_schemes", argNames: []);

  @override
  String crateApiSettingsConfigDefaults() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsConfigDefaultsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsConfigDefaultsConstMeta =>
      const TaskConstMeta(debugName: "config_defaults", argNames: []);

  @override
  String crateApiSettingsConfigFilePath() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsConfigFilePathConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsConfigFilePathConstMeta =>
      const TaskConstMeta(debugName: "config_file_path", argNames: []);

  @override
  Future<String> crateApiSettingsConfigLoad() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSettingsConfigLoadConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsConfigLoadConstMeta =>
      const TaskConstMeta(debugName: "config_load", argNames: []);

  @override
  Future<String> crateApiSettingsConfigSave({required String json}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSettingsConfigSaveConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsConfigSaveConstMeta =>
      const TaskConstMeta(debugName: "config_save", argNames: ["json"]);

  @override
  Future<String> crateApiSettingsDefaultProfile() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsDefaultProfileConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsDefaultProfileConstMeta =>
      const TaskConstMeta(debugName: "default_profile", argNames: []);

  @override
  String crateApiSftpDownloadsDir() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSftpDownloadsDirConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpDownloadsDirConstMeta =>
      const TaskConstMeta(debugName: "downloads_dir", argNames: []);

  @override
  String crateApiSettingsHighlightPatternError({required String pattern}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pattern, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsHighlightPatternErrorConstMeta,
        argValues: [pattern],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsHighlightPatternErrorConstMeta =>
      const TaskConstMeta(
        debugName: "highlight_pattern_error",
        argNames: ["pattern"],
      );

  @override
  Future<String> crateApiSettingsProfilesList() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsProfilesListConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsProfilesListConstMeta =>
      const TaskConstMeta(debugName: "profiles_list", argNames: []);

  @override
  Future<void> crateApiSettingsSecretDelete({
    required String kind,
    required String profileId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(kind, serializer);
          sse_encode_String(profileId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSettingsSecretDeleteConstMeta,
        argValues: [kind, profileId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsSecretDeleteConstMeta =>
      const TaskConstMeta(
        debugName: "secret_delete",
        argNames: ["kind", "profileId"],
      );

  @override
  Future<bool> crateApiSettingsSecretExists({
    required String kind,
    required String profileId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(kind, serializer);
          sse_encode_String(profileId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsSecretExistsConstMeta,
        argValues: [kind, profileId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsSecretExistsConstMeta =>
      const TaskConstMeta(
        debugName: "secret_exists",
        argNames: ["kind", "profileId"],
      );

  @override
  Future<void> crateApiSettingsSecretSet({
    required String kind,
    required String profileId,
    required String value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(kind, serializer);
          sse_encode_String(profileId, serializer);
          sse_encode_String(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSettingsSecretSetConstMeta,
        argValues: [kind, profileId, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsSecretSetConstMeta => const TaskConstMeta(
    debugName: "secret_set",
    argNames: ["kind", "profileId", "value"],
  );

  @override
  Future<List<String>> crateApiSettingsSerialPorts() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsSerialPortsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsSerialPortsConstMeta =>
      const TaskConstMeta(debugName: "serial_ports", argNames: []);

  @override
  void crateApiSettingsSetLanguage({required String code}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(code, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsSetLanguageConstMeta,
        argValues: [code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsSetLanguageConstMeta =>
      const TaskConstMeta(debugName: "set_language", argNames: ["code"]);

  @override
  Future<void> crateApiSftpSftpClose({required int id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSftpSftpCloseConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpCloseConstMeta =>
      const TaskConstMeta(debugName: "sftp_close", argNames: ["id"]);

  @override
  Stream<SftpProgress> crateApiSftpSftpDownload({
    required int id,
    required String remote,
    required String local,
  }) {
    final sink = RustStreamSink<SftpProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_u_32(id, serializer);
            sse_encode_String(remote, serializer);
            sse_encode_String(local, serializer);
            sse_encode_StreamSink_sftp_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 17,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiSftpSftpDownloadConstMeta,
          argValues: [id, remote, local, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSftpSftpDownloadConstMeta => const TaskConstMeta(
    debugName: "sftp_download",
    argNames: ["id", "remote", "local", "sink"],
  );

  @override
  Future<String> crateApiSftpSftpHome({required int id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSftpSftpHomeConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpHomeConstMeta =>
      const TaskConstMeta(debugName: "sftp_home", argNames: ["id"]);

  @override
  Future<List<SftpFileEntry>> crateApiSftpSftpList({
    required int id,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_sftp_file_entry,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSftpSftpListConstMeta,
        argValues: [id, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpListConstMeta =>
      const TaskConstMeta(debugName: "sftp_list", argNames: ["id", "path"]);

  @override
  Future<void> crateApiSftpSftpMkdir({required int id, required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSftpSftpMkdirConstMeta,
        argValues: [id, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpMkdirConstMeta =>
      const TaskConstMeta(debugName: "sftp_mkdir", argNames: ["id", "path"]);

  @override
  Future<int> crateApiSftpSftpOpen({required int termId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(termId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSftpSftpOpenConstMeta,
        argValues: [termId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpOpenConstMeta =>
      const TaskConstMeta(debugName: "sftp_open", argNames: ["termId"]);

  @override
  Future<void> crateApiSftpSftpRemove({
    required int id,
    required String path,
    required bool isDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_String(path, serializer);
          sse_encode_bool(isDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSftpSftpRemoveConstMeta,
        argValues: [id, path, isDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpRemoveConstMeta => const TaskConstMeta(
    debugName: "sftp_remove",
    argNames: ["id", "path", "isDir"],
  );

  @override
  Future<void> crateApiSftpSftpRename({
    required int id,
    required String from,
    required String to,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_String(from, serializer);
          sse_encode_String(to, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSftpSftpRenameConstMeta,
        argValues: [id, from, to],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSftpSftpRenameConstMeta => const TaskConstMeta(
    debugName: "sftp_rename",
    argNames: ["id", "from", "to"],
  );

  @override
  Stream<SftpProgress> crateApiSftpSftpUpload({
    required int id,
    required String local,
    required String remote,
  }) {
    final sink = RustStreamSink<SftpProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_u_32(id, serializer);
            sse_encode_String(local, serializer);
            sse_encode_String(remote, serializer);
            sse_encode_StreamSink_sftp_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 24,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiSftpSftpUploadConstMeta,
          argValues: [id, local, remote, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSftpSftpUploadConstMeta => const TaskConstMeta(
    debugName: "sftp_upload",
    argNames: ["id", "local", "remote", "sink"],
  );

  @override
  String crateApiSettingsShellPath({
    required String path,
    required String profileJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(profileJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsShellPathConstMeta,
        argValues: [path, profileJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsShellPathConstMeta => const TaskConstMeta(
    debugName: "shell_path",
    argNames: ["path", "profileJson"],
  );

  @override
  Future<String> crateApiSettingsStateLoad() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSettingsStateLoadConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsStateLoadConstMeta =>
      const TaskConstMeta(debugName: "state_load", argNames: []);

  @override
  Future<void> crateApiSettingsStateSave({required String json}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSettingsStateSaveConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSettingsStateSaveConstMeta =>
      const TaskConstMeta(debugName: "state_save", argNames: ["json"]);

  @override
  void crateApiTerminalTermApplySettings() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermApplySettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermApplySettingsConstMeta =>
      const TaskConstMeta(debugName: "term_apply_settings", argNames: []);

  @override
  void crateApiTerminalTermClear({required int id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermClearConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermClearConstMeta =>
      const TaskConstMeta(debugName: "term_clear", argNames: ["id"]);

  @override
  void crateApiTerminalTermClose({required int id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermCloseConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermCloseConstMeta =>
      const TaskConstMeta(debugName: "term_close", argNames: ["id"]);

  @override
  String crateApiTerminalTermCwd({required int id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermCwdConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermCwdConstMeta =>
      const TaskConstMeta(debugName: "term_cwd", argNames: ["id"]);

  @override
  TermFrame? crateApiTerminalTermFrame({required int id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_term_frame,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermFrameConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermFrameConstMeta =>
      const TaskConstMeta(debugName: "term_frame", argNames: ["id"]);

  @override
  void crateApiTerminalTermInput({required int id, required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermInputConstMeta,
        argValues: [id, data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermInputConstMeta =>
      const TaskConstMeta(debugName: "term_input", argNames: ["id", "data"]);

  @override
  bool crateApiTerminalTermKey({
    required int id,
    required String key,
    required String text,
    required int mods,
    required bool altIsMeta,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_String(key, serializer);
          sse_encode_String(text, serializer);
          sse_encode_u_8(mods, serializer);
          sse_encode_bool(altIsMeta, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 34)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermKeyConstMeta,
        argValues: [id, key, text, mods, altIsMeta],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermKeyConstMeta => const TaskConstMeta(
    debugName: "term_key",
    argNames: ["id", "key", "text", "mods", "altIsMeta"],
  );

  @override
  String crateApiTerminalTermLineText({required int id, required int row}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_u_16(row, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermLineTextConstMeta,
        argValues: [id, row],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermLineTextConstMeta =>
      const TaskConstMeta(debugName: "term_line_text", argNames: ["id", "row"]);

  @override
  bool crateApiTerminalTermMouse({
    required int id,
    required int action,
    required int button,
    required int col,
    required int row,
    required int mods,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_u_8(action, serializer);
          sse_encode_u_8(button, serializer);
          sse_encode_u_16(col, serializer);
          sse_encode_u_16(row, serializer);
          sse_encode_u_8(mods, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 36)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermMouseConstMeta,
        argValues: [id, action, button, col, row, mods],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermMouseConstMeta => const TaskConstMeta(
    debugName: "term_mouse",
    argNames: ["id", "action", "button", "col", "row", "mods"],
  );

  @override
  Stream<TermEvent> crateApiTerminalTermOpen({
    required int id,
    required String profileJson,
    required TermSize size,
  }) {
    final sink = RustStreamSink<TermEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_u_32(id, serializer);
            sse_encode_String(profileJson, serializer);
            sse_encode_box_autoadd_term_size(size, serializer);
            sse_encode_StreamSink_term_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 37,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiTerminalTermOpenConstMeta,
          argValues: [id, profileJson, size, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiTerminalTermOpenConstMeta => const TaskConstMeta(
    debugName: "term_open",
    argNames: ["id", "profileJson", "size", "sink"],
  );

  @override
  void crateApiTerminalTermPaste({required int id, required String text}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 38)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermPasteConstMeta,
        argValues: [id, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermPasteConstMeta =>
      const TaskConstMeta(debugName: "term_paste", argNames: ["id", "text"]);

  @override
  void crateApiTerminalTermResize({required int id, required TermSize size}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_box_autoadd_term_size(size, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 39)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermResizeConstMeta,
        argValues: [id, size],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermResizeConstMeta =>
      const TaskConstMeta(debugName: "term_resize", argNames: ["id", "size"]);

  @override
  void crateApiTerminalTermScroll({
    required int id,
    required int lines,
    required int col,
    required int row,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_i_32(lines, serializer);
          sse_encode_u_16(col, serializer);
          sse_encode_u_16(row, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 40)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermScrollConstMeta,
        argValues: [id, lines, col, row],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermScrollConstMeta => const TaskConstMeta(
    debugName: "term_scroll",
    argNames: ["id", "lines", "col", "row"],
  );

  @override
  void crateApiTerminalTermScrollOffset({
    required int id,
    required int offset,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_u_32(offset, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 41)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermScrollOffsetConstMeta,
        argValues: [id, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermScrollOffsetConstMeta =>
      const TaskConstMeta(
        debugName: "term_scroll_offset",
        argNames: ["id", "offset"],
      );

  @override
  void crateApiTerminalTermScrollTo({required int id, required String target}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_String(target, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 42)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermScrollToConstMeta,
        argValues: [id, target],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermScrollToConstMeta =>
      const TaskConstMeta(
        debugName: "term_scroll_to",
        argNames: ["id", "target"],
      );

  @override
  bool crateApiTerminalTermSearch({
    required int id,
    required String pattern,
    required bool backwards,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_String(pattern, serializer);
          sse_encode_bool(backwards, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 43)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiTerminalTermSearchConstMeta,
        argValues: [id, pattern, backwards],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermSearchConstMeta => const TaskConstMeta(
    debugName: "term_search",
    argNames: ["id", "pattern", "backwards"],
  );

  @override
  void crateApiTerminalTermSearchClear({required int id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 44)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermSearchClearConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermSearchClearConstMeta =>
      const TaskConstMeta(debugName: "term_search_clear", argNames: ["id"]);

  @override
  void crateApiTerminalTermSelectAll({required int id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 45)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermSelectAllConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermSelectAllConstMeta =>
      const TaskConstMeta(debugName: "term_select_all", argNames: ["id"]);

  @override
  void crateApiTerminalTermSelectClear({required int id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 46)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermSelectClearConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermSelectClearConstMeta =>
      const TaskConstMeta(debugName: "term_select_clear", argNames: ["id"]);

  @override
  void crateApiTerminalTermSelectStart({
    required int id,
    required int col,
    required int row,
    required bool rightHalf,
    required int kind,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_u_16(col, serializer);
          sse_encode_u_16(row, serializer);
          sse_encode_bool(rightHalf, serializer);
          sse_encode_u_8(kind, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 47)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermSelectStartConstMeta,
        argValues: [id, col, row, rightHalf, kind],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermSelectStartConstMeta =>
      const TaskConstMeta(
        debugName: "term_select_start",
        argNames: ["id", "col", "row", "rightHalf", "kind"],
      );

  @override
  void crateApiTerminalTermSelectUpdate({
    required int id,
    required int col,
    required int row,
    required bool rightHalf,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_u_16(col, serializer);
          sse_encode_u_16(row, serializer);
          sse_encode_bool(rightHalf, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 48)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermSelectUpdateConstMeta,
        argValues: [id, col, row, rightHalf],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermSelectUpdateConstMeta =>
      const TaskConstMeta(
        debugName: "term_select_update",
        argNames: ["id", "col", "row", "rightHalf"],
      );

  @override
  String? crateApiTerminalTermSelectionText({required int id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 49)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermSelectionTextConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermSelectionTextConstMeta =>
      const TaskConstMeta(debugName: "term_selection_text", argNames: ["id"]);

  @override
  void crateApiTerminalTermZmodemUpload({
    required int id,
    required List<String> paths,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_list_String(paths, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 50)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTerminalTermZmodemUploadConstMeta,
        argValues: [id, paths],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTerminalTermZmodemUploadConstMeta =>
      const TaskConstMeta(
        debugName: "term_zmodem_upload",
        argNames: ["id", "paths"],
      );

  @override
  Future<UpdateInfo?> crateApiUpdateUpdateCheckDaily() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 51,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_update_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUpdateUpdateCheckDailyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateUpdateCheckDailyConstMeta =>
      const TaskConstMeta(debugName: "update_check_daily", argNames: []);

  @override
  Future<UpdateInfo> crateApiUpdateUpdateCheckNow() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 52,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_update_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiUpdateUpdateCheckNowConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateUpdateCheckNowConstMeta =>
      const TaskConstMeta(debugName: "update_check_now", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<SftpProgress> dco_decode_StreamSink_sftp_progress_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<TermEvent> dco_decode_StreamSink_term_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  TermFrame dco_decode_box_autoadd_term_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_term_frame(raw);
  }

  @protected
  TermSize dco_decode_box_autoadd_term_size(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_term_size(raw);
  }

  @protected
  UpdateInfo dco_decode_box_autoadd_update_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_update_info(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SftpFileEntry> dco_decode_list_sftp_file_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sftp_file_entry).toList();
  }

  @protected
  List<TermLine> dco_decode_list_term_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_term_line).toList();
  }

  @protected
  List<TermRun> dco_decode_list_term_run(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_term_run).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  TermFrame? dco_decode_opt_box_autoadd_term_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_term_frame(raw);
  }

  @protected
  UpdateInfo? dco_decode_opt_box_autoadd_update_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_update_info(raw);
  }

  @protected
  SftpFileEntry dco_decode_sftp_file_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SftpFileEntry(
      name: dco_decode_String(arr[0]),
      isDir: dco_decode_bool(arr[1]),
      isLink: dco_decode_bool(arr[2]),
      size: dco_decode_i_64(arr[3]),
      modified: dco_decode_i_64(arr[4]),
      permissions: dco_decode_u_32(arr[5]),
    );
  }

  @protected
  SftpProgress dco_decode_sftp_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SftpProgress(
      done: dco_decode_i_64(arr[0]),
      total: dco_decode_i_64(arr[1]),
      finished: dco_decode_bool(arr[2]),
      error: dco_decode_String(arr[3]),
    );
  }

  @protected
  TermEvent dco_decode_term_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TermEvent(
      kind: dco_decode_String(arr[0]),
      text: dco_decode_String(arr[1]),
    );
  }

  @protected
  TermFrame dco_decode_term_frame(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return TermFrame(
      cols: dco_decode_u_16(arr[0]),
      rows: dco_decode_u_16(arr[1]),
      lines: dco_decode_list_term_line(arr[2]),
      cursorCol: dco_decode_u_16(arr[3]),
      cursorRow: dco_decode_u_16(arr[4]),
      cursorShape: dco_decode_u_8(arr[5]),
      cursorVisible: dco_decode_bool(arr[6]),
      displayOffset: dco_decode_u_32(arr[7]),
      historySize: dco_decode_u_32(arr[8]),
      altScreen: dco_decode_bool(arr[9]),
      mouseReporting: dco_decode_bool(arr[10]),
      foreground: dco_decode_u_32(arr[11]),
      background: dco_decode_u_32(arr[12]),
      cursorColor: dco_decode_u_32(arr[13]),
    );
  }

  @protected
  TermLine dco_decode_term_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TermLine(
      hash: dco_decode_i_64(arr[0]),
      runs: dco_decode_list_term_run(arr[1]),
    );
  }

  @protected
  TermRun dco_decode_term_run(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return TermRun(
      col: dco_decode_u_16(arr[0]),
      width: dco_decode_u_16(arr[1]),
      text: dco_decode_String(arr[2]),
      fg: dco_decode_u_32(arr[3]),
      bg: dco_decode_u_32(arr[4]),
      flags: dco_decode_u_16(arr[5]),
    );
  }

  @protected
  TermSize dco_decode_term_size(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TermSize(
      cols: dco_decode_u_16(arr[0]),
      rows: dco_decode_u_16(arr[1]),
      cellWidth: dco_decode_u_16(arr[2]),
      cellHeight: dco_decode_u_16(arr[3]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UpdateInfo dco_decode_update_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return UpdateInfo(
      latest: dco_decode_String(arr[0]),
      url: dco_decode_String(arr[1]),
      newer: dco_decode_bool(arr[2]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<SftpProgress> sse_decode_StreamSink_sftp_progress_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<TermEvent> sse_decode_StreamSink_term_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  TermFrame sse_decode_box_autoadd_term_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_term_frame(deserializer));
  }

  @protected
  TermSize sse_decode_box_autoadd_term_size(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_term_size(deserializer));
  }

  @protected
  UpdateInfo sse_decode_box_autoadd_update_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_update_info(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SftpFileEntry> sse_decode_list_sftp_file_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SftpFileEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sftp_file_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<TermLine> sse_decode_list_term_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TermLine>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_term_line(deserializer));
    }
    return ans_;
  }

  @protected
  List<TermRun> sse_decode_list_term_run(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TermRun>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_term_run(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TermFrame? sse_decode_opt_box_autoadd_term_frame(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_term_frame(deserializer));
    } else {
      return null;
    }
  }

  @protected
  UpdateInfo? sse_decode_opt_box_autoadd_update_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_update_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SftpFileEntry sse_decode_sftp_file_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_isDir = sse_decode_bool(deserializer);
    var var_isLink = sse_decode_bool(deserializer);
    var var_size = sse_decode_i_64(deserializer);
    var var_modified = sse_decode_i_64(deserializer);
    var var_permissions = sse_decode_u_32(deserializer);
    return SftpFileEntry(
      name: var_name,
      isDir: var_isDir,
      isLink: var_isLink,
      size: var_size,
      modified: var_modified,
      permissions: var_permissions,
    );
  }

  @protected
  SftpProgress sse_decode_sftp_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_done = sse_decode_i_64(deserializer);
    var var_total = sse_decode_i_64(deserializer);
    var var_finished = sse_decode_bool(deserializer);
    var var_error = sse_decode_String(deserializer);
    return SftpProgress(
      done: var_done,
      total: var_total,
      finished: var_finished,
      error: var_error,
    );
  }

  @protected
  TermEvent sse_decode_term_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    return TermEvent(kind: var_kind, text: var_text);
  }

  @protected
  TermFrame sse_decode_term_frame(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cols = sse_decode_u_16(deserializer);
    var var_rows = sse_decode_u_16(deserializer);
    var var_lines = sse_decode_list_term_line(deserializer);
    var var_cursorCol = sse_decode_u_16(deserializer);
    var var_cursorRow = sse_decode_u_16(deserializer);
    var var_cursorShape = sse_decode_u_8(deserializer);
    var var_cursorVisible = sse_decode_bool(deserializer);
    var var_displayOffset = sse_decode_u_32(deserializer);
    var var_historySize = sse_decode_u_32(deserializer);
    var var_altScreen = sse_decode_bool(deserializer);
    var var_mouseReporting = sse_decode_bool(deserializer);
    var var_foreground = sse_decode_u_32(deserializer);
    var var_background = sse_decode_u_32(deserializer);
    var var_cursorColor = sse_decode_u_32(deserializer);
    return TermFrame(
      cols: var_cols,
      rows: var_rows,
      lines: var_lines,
      cursorCol: var_cursorCol,
      cursorRow: var_cursorRow,
      cursorShape: var_cursorShape,
      cursorVisible: var_cursorVisible,
      displayOffset: var_displayOffset,
      historySize: var_historySize,
      altScreen: var_altScreen,
      mouseReporting: var_mouseReporting,
      foreground: var_foreground,
      background: var_background,
      cursorColor: var_cursorColor,
    );
  }

  @protected
  TermLine sse_decode_term_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hash = sse_decode_i_64(deserializer);
    var var_runs = sse_decode_list_term_run(deserializer);
    return TermLine(hash: var_hash, runs: var_runs);
  }

  @protected
  TermRun sse_decode_term_run(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_col = sse_decode_u_16(deserializer);
    var var_width = sse_decode_u_16(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_fg = sse_decode_u_32(deserializer);
    var var_bg = sse_decode_u_32(deserializer);
    var var_flags = sse_decode_u_16(deserializer);
    return TermRun(
      col: var_col,
      width: var_width,
      text: var_text,
      fg: var_fg,
      bg: var_bg,
      flags: var_flags,
    );
  }

  @protected
  TermSize sse_decode_term_size(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cols = sse_decode_u_16(deserializer);
    var var_rows = sse_decode_u_16(deserializer);
    var var_cellWidth = sse_decode_u_16(deserializer);
    var var_cellHeight = sse_decode_u_16(deserializer);
    return TermSize(
      cols: var_cols,
      rows: var_rows,
      cellWidth: var_cellWidth,
      cellHeight: var_cellHeight,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UpdateInfo sse_decode_update_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_latest = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_newer = sse_decode_bool(deserializer);
    return UpdateInfo(latest: var_latest, url: var_url, newer: var_newer);
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_sftp_progress_Sse(
    RustStreamSink<SftpProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_sftp_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_term_event_Sse(
    RustStreamSink<TermEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_term_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_term_frame(
    TermFrame self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_term_frame(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_term_size(
    TermSize self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_term_size(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_update_info(
    UpdateInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_update_info(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_sftp_file_entry(
    List<SftpFileEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sftp_file_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_term_line(
    List<TermLine> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_term_line(item, serializer);
    }
  }

  @protected
  void sse_encode_list_term_run(List<TermRun> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_term_run(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_term_frame(
    TermFrame? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_term_frame(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_update_info(
    UpdateInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_update_info(self, serializer);
    }
  }

  @protected
  void sse_encode_sftp_file_entry(
    SftpFileEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.isDir, serializer);
    sse_encode_bool(self.isLink, serializer);
    sse_encode_i_64(self.size, serializer);
    sse_encode_i_64(self.modified, serializer);
    sse_encode_u_32(self.permissions, serializer);
  }

  @protected
  void sse_encode_sftp_progress(SftpProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.done, serializer);
    sse_encode_i_64(self.total, serializer);
    sse_encode_bool(self.finished, serializer);
    sse_encode_String(self.error, serializer);
  }

  @protected
  void sse_encode_term_event(TermEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_term_frame(TermFrame self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.cols, serializer);
    sse_encode_u_16(self.rows, serializer);
    sse_encode_list_term_line(self.lines, serializer);
    sse_encode_u_16(self.cursorCol, serializer);
    sse_encode_u_16(self.cursorRow, serializer);
    sse_encode_u_8(self.cursorShape, serializer);
    sse_encode_bool(self.cursorVisible, serializer);
    sse_encode_u_32(self.displayOffset, serializer);
    sse_encode_u_32(self.historySize, serializer);
    sse_encode_bool(self.altScreen, serializer);
    sse_encode_bool(self.mouseReporting, serializer);
    sse_encode_u_32(self.foreground, serializer);
    sse_encode_u_32(self.background, serializer);
    sse_encode_u_32(self.cursorColor, serializer);
  }

  @protected
  void sse_encode_term_line(TermLine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.hash, serializer);
    sse_encode_list_term_run(self.runs, serializer);
  }

  @protected
  void sse_encode_term_run(TermRun self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.col, serializer);
    sse_encode_u_16(self.width, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_u_32(self.fg, serializer);
    sse_encode_u_32(self.bg, serializer);
    sse_encode_u_16(self.flags, serializer);
  }

  @protected
  void sse_encode_term_size(TermSize self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.cols, serializer);
    sse_encode_u_16(self.rows, serializer);
    sse_encode_u_16(self.cellWidth, serializer);
    sse_encode_u_16(self.cellHeight, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_update_info(UpdateInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.latest, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_bool(self.newer, serializer);
  }
}
