// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `current_config`, `state_path`, `to_json`

/// 读取配置（缺失字段已补默认值）。文件损坏时返回错误，不静默覆盖用户的文件。
Future<String> configLoad() =>
    RustLib.instance.api.crateApiSettingsConfigLoad();

/// 校验并保存，返回规范化后的配置
Future<String> configSave({required String json}) =>
    RustLib.instance.api.crateApiSettingsConfigSave(json: json);

String configDefaults() =>
    RustLib.instance.api.crateApiSettingsConfigDefaults();

String configFilePath() =>
    RustLib.instance.api.crateApiSettingsConfigFilePath();

/// 内置（本地 shell、~/.ssh/config）+ 用户 profile
Future<String> profilesList() =>
    RustLib.instance.api.crateApiSettingsProfilesList();

Future<String> defaultProfile() =>
    RustLib.instance.api.crateApiSettingsDefaultProfile();

String colorSchemes() => RustLib.instance.api.crateApiSettingsColorSchemes();

Future<List<String>> serialPorts() =>
    RustLib.instance.api.crateApiSettingsSerialPorts();

/// kind: password / passphrase:<私钥路径>
Future<void> secretSet({
  required String kind,
  required String profileId,
  required String value,
}) => RustLib.instance.api.crateApiSettingsSecretSet(
  kind: kind,
  profileId: profileId,
  value: value,
);

Future<bool> secretExists({required String kind, required String profileId}) =>
    RustLib.instance.api.crateApiSettingsSecretExists(
      kind: kind,
      profileId: profileId,
    );

Future<void> secretDelete({required String kind, required String profileId}) =>
    RustLib.instance.api.crateApiSettingsSecretDelete(
      kind: kind,
      profileId: profileId,
    );

/// 拖文件进终端：按目标 shell 翻译路径并转义
String shellPath({required String path, required String profileJson}) => RustLib
    .instance
    .api
    .crateApiSettingsShellPath(path: path, profileJson: profileJson);

/// 窗口 / 标签页状态（恢复标签页用），内容由界面层定义
Future<String> stateLoad() => RustLib.instance.api.crateApiSettingsStateLoad();

Future<void> stateSave({required String json}) =>
    RustLib.instance.api.crateApiSettingsStateSave(json: json);

/// 界面语言变化时同步给 Rust（SSH 提示、连接错误等在终端里显示的文字）；code: zh / en
void setLanguage({required String code}) =>
    RustLib.instance.api.crateApiSettingsSetLanguage(code: code);
