// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `client`, `report`

/// 在终端会话的 SSH 连接上打开 SFTP，返回 SFTP 句柄 id
Future<int> sftpOpen({required int termId}) =>
    RustLib.instance.api.crateApiSftpSftpOpen(termId: termId);

Future<String> sftpHome({required int id}) =>
    RustLib.instance.api.crateApiSftpSftpHome(id: id);

Future<List<SftpFileEntry>> sftpList({required int id, required String path}) =>
    RustLib.instance.api.crateApiSftpSftpList(id: id, path: path);

Future<void> sftpMkdir({required int id, required String path}) =>
    RustLib.instance.api.crateApiSftpSftpMkdir(id: id, path: path);

Future<void> sftpRename({
  required int id,
  required String from,
  required String to,
}) => RustLib.instance.api.crateApiSftpSftpRename(id: id, from: from, to: to);

Future<void> sftpRemove({
  required int id,
  required String path,
  required bool isDir,
}) => RustLib.instance.api.crateApiSftpSftpRemove(
  id: id,
  path: path,
  isDir: isDir,
);

Stream<SftpProgress> sftpDownload({
  required int id,
  required String remote,
  required String local,
}) => RustLib.instance.api.crateApiSftpSftpDownload(
  id: id,
  remote: remote,
  local: local,
);

Stream<SftpProgress> sftpUpload({
  required int id,
  required String local,
  required String remote,
}) => RustLib.instance.api.crateApiSftpSftpUpload(
  id: id,
  local: local,
  remote: remote,
);

Future<void> sftpClose({required int id}) =>
    RustLib.instance.api.crateApiSftpSftpClose(id: id);

/// 下载默认存到“下载”文件夹
String downloadsDir() => RustLib.instance.api.crateApiSftpDownloadsDir();

class SftpFileEntry {
  final String name;
  final bool isDir;
  final bool isLink;
  final PlatformInt64 size;
  final PlatformInt64 modified;
  final int permissions;

  const SftpFileEntry({
    required this.name,
    required this.isDir,
    required this.isLink,
    required this.size,
    required this.modified,
    required this.permissions,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      isDir.hashCode ^
      isLink.hashCode ^
      size.hashCode ^
      modified.hashCode ^
      permissions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SftpFileEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isDir == other.isDir &&
          isLink == other.isLink &&
          size == other.size &&
          modified == other.modified &&
          permissions == other.permissions;
}

/// 传输进度；finished=true 时 error 为空表示成功
class SftpProgress {
  final PlatformInt64 done;
  final PlatformInt64 total;
  final bool finished;
  final String error;

  const SftpProgress({
    required this.done,
    required this.total,
    required this.finished,
    required this.error,
  });

  @override
  int get hashCode =>
      done.hashCode ^ total.hashCode ^ finished.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SftpProgress &&
          runtimeType == other.runtimeType &&
          done == other.done &&
          total == other.total &&
          finished == other.finished &&
          error == other.error;
}
