// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `session_by_id`, `session`, `to_core`

/// 打开会话。id 由 Dart 分配，事件流在会话结束（exit）后自然停止。
Stream<TermEvent> termOpen({
  required int id,
  required String profileJson,
  required TermSize size,
}) => RustLib.instance.api.crateApiTerminalTermOpen(
  id: id,
  profileJson: profileJson,
  size: size,
);

TermFrame? termFrame({required int id}) =>
    RustLib.instance.api.crateApiTerminalTermFrame(id: id);

/// 直接写入（快捷键动作发出的固定序列）
void termInput({required int id, required List<int> data}) =>
    RustLib.instance.api.crateApiTerminalTermInput(id: id, data: data);

void termPaste({required int id, required String text}) =>
    RustLib.instance.api.crateApiTerminalTermPaste(id: id, text: text);

/// 返回 false 表示这个键不产生终端输入
bool termKey({
  required int id,
  required String key,
  required String text,
  required int mods,
  required bool altIsMeta,
}) => RustLib.instance.api.crateApiTerminalTermKey(
  id: id,
  key: key,
  text: text,
  mods: mods,
  altIsMeta: altIsMeta,
);

/// action: 0 按下 1 抬起 2 移动；返回 true 表示已作为鼠标上报发给程序
bool termMouse({
  required int id,
  required int action,
  required int button,
  required int col,
  required int row,
  required int mods,
}) => RustLib.instance.api.crateApiTerminalTermMouse(
  id: id,
  action: action,
  button: button,
  col: col,
  row: row,
  mods: mods,
);

/// lines > 0 向上
void termScroll({
  required int id,
  required int lines,
  required int col,
  required int row,
}) => RustLib.instance.api.crateApiTerminalTermScroll(
  id: id,
  lines: lines,
  col: col,
  row: row,
);

/// top / bottom / page-up / page-down / up / down
void termScrollTo({required int id, required String target}) =>
    RustLib.instance.api.crateApiTerminalTermScrollTo(id: id, target: target);

/// 滚动条拖动：offset = 距离底部的行数
void termScrollOffset({required int id, required int offset}) => RustLib
    .instance
    .api
    .crateApiTerminalTermScrollOffset(id: id, offset: offset);

void termResize({required int id, required TermSize size}) =>
    RustLib.instance.api.crateApiTerminalTermResize(id: id, size: size);

/// kind: 0 普通 1 单词 2 整行 3 块
void termSelectStart({
  required int id,
  required int col,
  required int row,
  required bool rightHalf,
  required int kind,
}) => RustLib.instance.api.crateApiTerminalTermSelectStart(
  id: id,
  col: col,
  row: row,
  rightHalf: rightHalf,
  kind: kind,
);

void termSelectUpdate({
  required int id,
  required int col,
  required int row,
  required bool rightHalf,
}) => RustLib.instance.api.crateApiTerminalTermSelectUpdate(
  id: id,
  col: col,
  row: row,
  rightHalf: rightHalf,
);

void termSelectAll({required int id}) =>
    RustLib.instance.api.crateApiTerminalTermSelectAll(id: id);

void termSelectClear({required int id}) =>
    RustLib.instance.api.crateApiTerminalTermSelectClear(id: id);

String? termSelectionText({required int id}) =>
    RustLib.instance.api.crateApiTerminalTermSelectionText(id: id);

String termLineText({required int id, required int row}) =>
    RustLib.instance.api.crateApiTerminalTermLineText(id: id, row: row);

bool termSearch({
  required int id,
  required String pattern,
  required bool backwards,
}) => RustLib.instance.api.crateApiTerminalTermSearch(
  id: id,
  pattern: pattern,
  backwards: backwards,
);

void termSearchClear({required int id}) =>
    RustLib.instance.api.crateApiTerminalTermSearchClear(id: id);

void termClear({required int id}) =>
    RustLib.instance.api.crateApiTerminalTermClear(id: id);

/// 远端 rz 在等上传时，界面选好的文件；空列表 = 取消
void termZmodemUpload({required int id, required List<String> paths}) =>
    RustLib.instance.api.crateApiTerminalTermZmodemUpload(id: id, paths: paths);

/// 关闭连接并释放会话
void termClose({required int id}) =>
    RustLib.instance.api.crateApiTerminalTermClose(id: id);

/// 本地 shell 当前工作目录（新标签页继承目录用），拿不到返回空
String termCwd({required int id}) =>
    RustLib.instance.api.crateApiTerminalTermCwd(id: id);

/// 配色 / 字体等设置变更后，已打开的会话立即换配色
void termApplySettings() =>
    RustLib.instance.api.crateApiTerminalTermApplySettings();

/// kind: wakeup / title / bell / copy / exit / status / zmodem-upload
class TermEvent {
  final String kind;
  final String text;

  const TermEvent({required this.kind, required this.text});

  @override
  int get hashCode => kind.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TermEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          text == other.text;
}

class TermFrame {
  final int cols;
  final int rows;
  final List<TermLine> lines;
  final int cursorCol;
  final int cursorRow;
  final int cursorShape;
  final bool cursorVisible;
  final int displayOffset;
  final int historySize;
  final bool altScreen;
  final bool mouseReporting;
  final int foreground;
  final int background;
  final int cursorColor;

  const TermFrame({
    required this.cols,
    required this.rows,
    required this.lines,
    required this.cursorCol,
    required this.cursorRow,
    required this.cursorShape,
    required this.cursorVisible,
    required this.displayOffset,
    required this.historySize,
    required this.altScreen,
    required this.mouseReporting,
    required this.foreground,
    required this.background,
    required this.cursorColor,
  });

  @override
  int get hashCode =>
      cols.hashCode ^
      rows.hashCode ^
      lines.hashCode ^
      cursorCol.hashCode ^
      cursorRow.hashCode ^
      cursorShape.hashCode ^
      cursorVisible.hashCode ^
      displayOffset.hashCode ^
      historySize.hashCode ^
      altScreen.hashCode ^
      mouseReporting.hashCode ^
      foreground.hashCode ^
      background.hashCode ^
      cursorColor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TermFrame &&
          runtimeType == other.runtimeType &&
          cols == other.cols &&
          rows == other.rows &&
          lines == other.lines &&
          cursorCol == other.cursorCol &&
          cursorRow == other.cursorRow &&
          cursorShape == other.cursorShape &&
          cursorVisible == other.cursorVisible &&
          displayOffset == other.displayOffset &&
          historySize == other.historySize &&
          altScreen == other.altScreen &&
          mouseReporting == other.mouseReporting &&
          foreground == other.foreground &&
          background == other.background &&
          cursorColor == other.cursorColor;
}

class TermLine {
  final PlatformInt64 hash;
  final List<TermRun> runs;

  const TermLine({required this.hash, required this.runs});

  @override
  int get hashCode => hash.hashCode ^ runs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TermLine &&
          runtimeType == other.runtimeType &&
          hash == other.hash &&
          runs == other.runs;
}

class TermRun {
  final int col;
  final int width;
  final String text;
  final int fg;
  final int bg;
  final int flags;

  const TermRun({
    required this.col,
    required this.width,
    required this.text,
    required this.fg,
    required this.bg,
    required this.flags,
  });

  @override
  int get hashCode =>
      col.hashCode ^
      width.hashCode ^
      text.hashCode ^
      fg.hashCode ^
      bg.hashCode ^
      flags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TermRun &&
          runtimeType == other.runtimeType &&
          col == other.col &&
          width == other.width &&
          text == other.text &&
          fg == other.fg &&
          bg == other.bg &&
          flags == other.flags;
}

class TermSize {
  final int cols;
  final int rows;
  final int cellWidth;
  final int cellHeight;

  const TermSize({
    required this.cols,
    required this.rows,
    required this.cellWidth,
    required this.cellHeight,
  });

  @override
  int get hashCode =>
      cols.hashCode ^ rows.hashCode ^ cellWidth.hashCode ^ cellHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TermSize &&
          runtimeType == other.runtimeType &&
          cols == other.cols &&
          rows == other.rows &&
          cellWidth == other.cellWidth &&
          cellHeight == other.cellHeight;
}
