// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_info`

/// 当前版本（Cargo 包版本，界面显示也用它）
String appVersion() => RustLib.instance.api.crateApiUpdateAppVersion();

/// 启动时后台检查：24 小时内最多请求一次；只有新版本时返回，失败静默
Future<UpdateInfo?> updateCheckDaily() =>
    RustLib.instance.api.crateApiUpdateUpdateCheckDaily();

/// “关于”页的立即检查
Future<UpdateInfo> updateCheckNow() =>
    RustLib.instance.api.crateApiUpdateUpdateCheckNow();

class UpdateInfo {
  /// 最新发布的 tag；还没有任何发布时为空
  final String latest;
  final String url;
  final bool newer;

  const UpdateInfo({
    required this.latest,
    required this.url,
    required this.newer,
  });

  @override
  int get hashCode => latest.hashCode ^ url.hashCode ^ newer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateInfo &&
          runtimeType == other.runtimeType &&
          latest == other.latest &&
          url == other.url &&
          newer == other.newer;
}
